In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Computer.use_jedi = False
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

numpy 파일 입출력

numpy는 배열 객체를 바이너리(2진) 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.

In [2]:
# 메소드 이름    기능                                                   파일 포맷
# save()         numpy 배열 객체 1개를 바이너리 파일로 저장한다.        바이너리
# savez()        numpy 배열 객체 여러 개를 바이너리 파일로 저장한다.    바이너리
# load()         numpy 배열 저장 파일로 부터 배열 객체를 읽어온다.      바이너리
# ====================================================================================
# savetxt()      numpy 배열 객체를 텍스트 파일로 저장한다.              텍스트
# loadtxt()      텍스트 파일에 저장된 numpy 배열 객체를 읽어온다.       텍스트

In [3]:
a = np.random.randint(0, 10, (2, 3))
print(a)
b = np.random.randint(0, 10, (2, 3))
print(b)

[[0 7 0]
 [7 2 4]]
[[7 1 2]
 [4 3 9]]


numpy 배열 객체를 바이너리 파일로 저장

In [4]:
# save(), savez() 메소드를 사용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# save(): 배열 1개를 저장한다. 확장명 => npy
# savez(): 배열 여러 개를 저장한다. 확장명 => npz

# a 배열을 바이너리 파일로 저장한다.
# save('경로명', 배열명)
np.save('./output/my_array1', a)

# a, b 배열을 바이너리 파일로 저장한다.
# savez('경로명', 배열명1, 배열명2, ...)
np.savez('./output/my_array2', a, b)

FileNotFoundError: [Errno 2] No such file or directory: './output/my_array1.npy'

바이너리 파일로 저장된 numpy 배열 객체 읽어오기

In [ ]:
# load() 메소드로 npy, npz 파일로 부터 데이터를 읽어올 수 있다.
# npy 파일 읽기
# 저장할 때는 메소드가 달라서 확장명이 다르게 붙기 때문에 파일명만 입력하면 되지만 읽어올 때는 읽어올 때는 메소드가
# 같아서 확장명 까지 입력해야 한다.
# load('경로명')
print(np.load('./output/my_array1.npy'))

In [ ]:
# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
npzFile = np.load('./output/my_array2.npz')
print(npzFile['arr_0'])
print(npzFile['arr_1'])

numpy 배열 객체를 텍스트 파일로 저장

In [ ]:
c = np.random.random((3, 4))
print(c)

In [ ]:
# 텍스트 파일은 확장명이 txt인 파일을 의미하는 것이 아니고 확장명이 csv 또는 tsv인 파일을 의미한다.
# savetxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장할 수 있다.
# savetxt('경로명', 배열명, delimiter='구분자')
np.savetxt('./output/saved.csv', c, delimiter=',') # csv 파일은 데이터를 ','로 구분한다.
np.savetxt('./output/saved.tsv', c, delimiter='\t') # tsv 파일은 데이터를 tab으로 구분한다.

텍스트 파일로 저장된 numpy 배열 객체 읽어오기

In [ ]:
# loadtxt() 메소드로 텍스트 파일로 저장된 numpy 배열 객체를 읽어올 수 있다.
# loadtxt('경로명', dtype, delimiter='구분자')
print(np.loadtxt('./output/saved.csv', dtype=np.float, delimiter=','))
print(np.loadtxt('./output/saved.tsv', dtype=np.int, delimiter='\t'))

배열(행렬) 연산 - 산술 연산

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

In [ ]:
# 덧셈: +, add()
print(a + b)
print(np.add(a, b))

In [ ]:
# 뺄셈: -, subtract()
print(a - b)
print(np.subtract(a, b))

In [ ]:
# 곱셈: *, multiply()
print(a * b)
print(np.multiply(a, b))

In [ ]:
# 나눗셈: /, divide()
print(a / b)
print(np.divide(a, b))

In [ ]:
print(a // b)
print(a % b)

In [ ]:
# 지수
print(np.exp(a))

In [ ]:
# 제곱근
print(np.sqrt(a))

In [ ]:
# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

In [ ]:
# 로그
print(np.log(a))

In [ ]:
# 행렬의 내적
print(np.dot(a, b))

<img src="./images/dot.png" align="left" width="800"/>

배열(행렬) 연산 - 비교 연산

In [ ]:
# 배열 요소별 비교: >, >=, <, <=, ==, !=
print(a == b)

In [ ]:
# 배열 전체 비교: array_equal() 메소드
print(np.array_equal(a, b))

집계 함수

numpy의 모든 집계 함수는 axis를 기준으로 게산하며 집계 함수에 axis를 지정하지 않으면 None이 기본값으로 사용된다.

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

합계: 넘파이배열.sum(), np.sum(넘파이배열)

In [ ]:
# axis=None
# axis=None은 전체 배열을 행과 열을 구분하지 않고 전체 합계를 계산한다. 생략시 기본값으로 사용된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

<img src="./images/numpyImage02.jpg" align="left" width="200"/>

In [ ]:
# axis=0
# axis=0은 행을 기준으로 각 행의 동일한 인덱스 요소를 그룹으로 계산한다. => 각 열의 합계
print(a.sum(axis=0))
print(np.sum(a, axis=0))

<img src="./images/numpyImage03.jpg" align="left" width="200"/>

In [ ]:
# axis=1
# axis=1은 열을 기준으로 각 열의 동일한 인덱스 요소를 그룹으로 계산한다. => 각 행의 합계
print(a.sum(axis=1))
print(np.sum(a, axis=1))

<img src="./images/numpyImage04.jpg" align="left" width="200"/>

최대값: 넘파이배열.max(), np.max(넘파이배열), 최소값: 넘파이배열.min(), np.min(넘파이배열)

In [ ]:
print(a.max()) # print(a.max(axis=None))
print(np.max(a)) # print(np.max(a, axis=None))
print(a.min()) # print(a.min(axis=None))
print(np.min(a)) # print(np.min(a, axis=None))

In [ ]:
print(a.max(axis=0))
print(np.max(a, axis=0))
print(a.min(axis=0))
print(np.min(a, axis=0))

In [ ]:
print(a.max(axis=1))
print(np.max(a, axis=1))
print(a.min(axis=1))
print(np.min(a, axis=1))

누적 합계: 넘파이배열.cumsum(), np.cumsum(넘파이배열)

In [ ]:
print(a.cumsum()) # print(a.cumsum(axis=None))
print(np.cumsum(a)) # print(np.cumsum(a, axis=None))

In [ ]:
print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

In [ ]:
print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))

평균: 넘파이배열.mean(), np.mean(넘파이배열)

In [ ]:
print(a.mean()) # print(a.mean(axis=None))
print(np.mean(a)) # print(np.mean(a, axis=None))

In [ ]:
print(a.mean(axis=0))
print(np.mean(a, axis=0))

In [ ]:
print(a.mean(axis=1))
print(np.mean(a, axis=1))

중위수: np.median(넘파이배열)

In [ ]:
print(np.median(a)) # print(np.mean(a, axis=None))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

상관계수: np.corrcoef(넘파이배열)

In [ ]:
print(np.corrcoef(a)) # axis를 사용하지 않는다.

표준편차: 넘파이배열.std(), np.std(넘파이배열)

In [ ]:
print(a.std()) # print(a.std(axis=None))
print(np.std(a)) # print(np.std(a, axis=None))

In [ ]:
print(a.std(axis=0))
print(np.std(a, axis=0))

In [ ]:
print(a.std(axis=1))
print(np.std(a, axis=1))

브로드 캐스팅 

shape이 같은 두 배열에 대한 이항 연산은 배열 요소별로 실행된다. 
두 배열의 shape이 다를 경우 두 배열 간의 형상(모양)을 맞추는 그림과 같은 브로드캐스팅 과정을 거쳐서 실행된다. 
<img src="./images/numpyImage05.jpg" align="center" width="500"/>

In [6]:
a = np.arange(1, 25).reshape(4, 6)
pprint(a)
b = np.arange(25, 49).reshape(4, 6)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [9]:
# shape이 같은 배열을 이항 연산할 경우 위치가 같은 요소 단위로 실행된다. 
print(a + b)

[[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


In [11]:
# 배열과 스칼라(단일 값)의 연산
# 배열과 스칼라 사이의 이항 연산 시 스칼라를 배열로 변환한다. 
a = np.arange(1, 25).reshape(4, 6)
print(a)
print(a + 100)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [14]:
# a + 100은 다음과 같은 과정을 거쳐서 처리된다. 
new_arr = np.full_like(a, 100)
print(new_arr)
print(a + new_arr)

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [17]:
# shape이 다른 배열의 연산 
a = np.arange(5).reshape(1, 5)
print(a)

[[0 1 2 3 4]]


벡터 연산 

numpy는 벡터연산을 지원한다. 
numpy 집합 연산에는 벡터화 기능이 적용되어 있어서 벡터 처리에 대해 벡터 연산을 적용할 경우 처리 속도가 100배 이상 빠르다. 

In [19]:
a = np.arange(10000000, dtype=np.int64)

In [21]:
%%time
result = 0
for i in a:
    result += i
print(result)

49999995000000
CPU times: total: 3.94 s
Wall time: 4.03 s


In [22]:
%%time
result = np.sum(a)
print(result)

49999995000000
CPU times: total: 15.6 ms
Wall time: 18 ms


배열 복사 

nbarray 배열 객체에 대한 인덱싱, 슬라이싱이 반환하는 배열은 새로운 객체가 아닌 기존 배열의 view이다. 
반환된 배열의 값을 변경하면 원본 배열에 변경한 값이 반영된다.

In [26]:
a = np.random.randint(0, 9, (3, 3))
print(a)
print(a[0])

[[2 1 6]
 [0 2 7]
 [8 4 7]]
[2 1 6]
